config/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include
from landing.views import home_view

from feed.models import Feed
from account.models import Profile
from django.contrib.auth.models import User


urlpatterns = [
    path('accounts/', include('account.urls')),
    path('accounts/', include(('django.contrib.auth.urls', 'auth'), namespace='accounts')),
    path('admin/', admin.site.urls),
    path('feeds/', include('feed.urls')),
    path('notifications/', include('notification.urls')),
    path('messages/', include('direct_message.urls')),
    path('search/', include('landing.urls') ),
    path('', include('landing.urls')),

    # api routes

    path('api/feeds/', include(('feed.api.urls', 'feed_api'))),

]

feed/api/urls.py
from django.urls import path

from feed.api.views import feed_list, feed_detail
from feed.api.views import FeedViewSet

urlpatterns = [
    path('', feed_list),
    path('<int:pk>/', feed_detail),
]

feed/urls.py
from django.urls import path
from .views import feed_list, feed_create_view, comment_feed, like_feed, feed_detail, api_like_feed


app_name = 'feed'
urlpatterns = [
   
    path("", feed_list, name="feed_list"),
    path("", feed_list, name="feed_list"),
    path('<int:pk>/', feed_detail, name='feed_detail'),
    path("create/", feed_create_view, name="feed_create"),
    path("<int:pk>/comments/create", comment_feed, name="comment_feed"),
    path("<int:pk>/likes/add", like_feed, name="like_feed"),
]

feed/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse


class Feed(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='feeds', on_delete=models.CASCADE)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
     
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='feeds_liked', blank=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.content[:100]

    def get_absolute_url(self):
        return reverse("feed:feed_detail", kwargs={"pk": self.pk})

    
    
class Comment(models.Model):
    content = models.TextField()
    feed = models.ForeignKey(Feed, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='comments', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

feed/forms.py
from django import forms

from .models import Feed, Comment

class FeedCreateForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={
        'rows': 3,
        'class': 'form-group input-text',
        'placeholder': 'Say something...'

    }))
    class Meta:
        model = Feed
        fields = ['content']

class CommentCreateForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={
        'rows': 1,
        'class': 'form-group input-text',
        'placeholder': 'Add a comment...'

    }))
    class Meta:
        model = Comment
        fields = ['content']

feed/api/views.py
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser

from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework.response import Response
from rest_framework import serializers, viewsets, permissions

from feed.models import Feed
from feed.api.serializers import FeedSerializer



@csrf_exempt
def feed_list(request):
    """
    List all code snippets, or create a new snippet.
    """
    if request.method == 'GET':
        feeds = Feed.objects.all()
        serializer = FeedSerializer(feeds, many=True)
        return JsonResponse(serializer.data, safe=False)

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        data.user = request.user
        serializer = FeedSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=201)
        return JsonResponse(serializer.errors, status=400)

@csrf_exempt
def feed_detail(request, pk):
    """
    Retrieve, update or delete a code snippet.
    """
    try:
        feed = Feed.objects.get(pk=pk)
    except Feed.DoesNotExist:
        return HttpResponse(status=404)

    if request.method == 'GET':
        serializer = FeedSerializer(feed)
        return JsonResponse(serializer.data)
    if request.method == 'PUT':
        data = JSONParser().parse(request)
        serializer = FeedSerializer(feed, data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data)
        return JsonResponse(serializer.errors, status=400)
    if request.method == 'DELETE':
        feed.delete()
        return HttpResponse(status=204)















# @api_view(['GET'])
# def all_feeds(request):
#     if request.method == 'GET':
#         feeds = Feed.objects.all()
#         serializer = FeedSerializer(feeds, many=True)
#         return response(serializer.data)

# @api_view(['GET']):
# def feed(request, pk):
#     try:
#         feed = Feed.objects.get(pk=pk)
#     except Feed.DoesNotExist:
#         return HttpResponse(status=404)

#     if request.method == 'GET':
#         serializer = FeedSerializer(feed)
#         return Response(serializer.data)

class FeedViewSet(viewsets.ModelViewSet):
    queryset = Feed.objects.all()
    serializer_class = FeedSerializer
    authentication_classes =[]
    permission_classes = []

feed/views.py
from django.contrib.auth.decorators import login_required
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render

from .models import Feed, Comment
from notification.models import Notification

from .forms import FeedCreateForm, CommentCreateForm

@login_required
def feed_list(request):
    feeds = Feed.objects.all()
    feed_form = FeedCreateForm()
    comment_form = CommentCreateForm
    context = {'feeds' : feeds, 'feed_form': feed_form, 'comment_form': comment_form}
    return render(request, 'feed/feed_list.html', context)

def feed_detail(request, pk):
    feed = get_object_or_404(Feed, pk=pk)
    comments = feed.comments.all()
    form = CommentCreateForm()
    context = {
        'feed': feed,
        'comments': comments,
        'form' : form
    }
    return render(request, 'feed/feed_detail.html', context)

@login_required
def feed_create_view(request):
    if request.method == 'POST':
        form = FeedCreateForm(request.POST)
        if form.is_valid():
            feed = form.save(commit=False)
            feed.user = request.user
            feed.save()
            return redirect('feed:feed_list')
    else:
        form = FeedCreateForm()

    context = {
        'form' : form
    }
    return render(request, 'feed/feed_create.html', context)


@login_required
def like_feed(request, pk):
    feed = get_object_or_404(Feed, pk=pk)

    if request.user in feed.likes.all():
        feed.likes.remove(request.user)
        feed.save()
    else:
        feed.likes.add(request.user)
        if request.user != feed.user:
            Notification.objects.create(user=request.user, type='like', target_model=feed.pk, target=feed.user)
        feed.save()
    
    return redirect('feed:feed_list')

@login_required
def comment_feed(request, pk):
    feed = get_object_or_404(Feed, pk=pk)

    if request.method == 'POST':
        form = CommentCreateForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.feed = feed
            new_comment.save()
            # return redirect(feed)
            if new_comment.user != feed.user:
                Notification.objects.create(user=request.user, type='comment', target_model=feed.pk, target=feed.user)
            return redirect('feed:feed_list')

    else:
        form = CommentCreateForm()

    context = {
        'feed': feed,
        'form': form
    }
    
    return render(request, 'feed/comment_create.html', context)




def api_like_feed(request):
    
    response = {
        'ok': 'ok',

    }
    return JsonResponse(response)

feed/templates/feed/comment_create.html
{% extends 'base.html' %}

{% block content %}
    <section>
        <form action="" method="post">
            <div class="form-groups">
                {% csrf_token %}
                {{ form.content }}
                <button type="submit" class="btn btn-black">Post</button>
            </div>
        </form>
    </section>
{% endblock content %}

feed/templates/feed/feed_create.html
{% extends 'base.html' %}

{% block content %}
    <section>
        <form action="{% url 'feed:feed_create' %}" method="post">
            <div class="form-groups">
                {% csrf_token %}
                {{ form.content }}
                <button type="submit" class="btn btn-black">Post</button>
            </div>
        </form>
    </section>
{% endblock content %}

feed/templates/feed/feed_detail.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}
        <section class="feed-detail">
            <article class="feed">
                <header class="feed-header">
                    <a href="{% url 'profile' feed.user.pk %}" class="feed-user">{{ feed.user }}</a>
                    <span class="feed-date">{{ feed.created | naturaltime }}</span>
                </header>
                <div class="feed-body">
                    <p>{{ feed.content }}</p>
                </div>
                <footer class="feed-footer">
                    <div class="feed-info">
                        <a href="{% url 'feed:like_feed' feed.pk %}" class="feed-like-icon feed-detail-like" data-feed-id="{{feed.pk }}" data-action=
                        {% if request.user in feed.likes.all %}
                        'unlike'
                        {% endif %}
                        'like'
                        >
                            {% if request.user in feed.likes.all %}
                            👍
                            {% else %}
                            👍🏼
                            {% endif %}
                        </a>
                        <div class="feed-like-info">
                            <span class="feed-like-number">{{ feed.likes.all | length}}</span>
                            <span>like{{ feed.likes.count| pluralize}}</span>
                        </div>
                        <div class="feed-comment-info">
                            <span class="feed-comment-number">{{ feed.comments.all | length}}</span>
                            <span>comment{{ feed.comments.count| pluralize}}</span>
                        </div>
                    </div>
                </footer>
            </article>
            <h3>Comments</h3>
            <article class="feed-comments">
                {% for comment in comments %}
                
                <div class="comment">
                    <a href="{% url 'profile' comment.user.pk %}"><strong>{{ comment.user }} </strong></a>
                    <p>{{ comment.content }}</p>
                </div>
                {% empty %}
                    {% if feed.user != request.user %}     
                        Be the first one to comment on this post.
                    {% else %}
                        No comments yet.
                    {% endif %}
                {% endfor %}
            </article>
            
            <form class="comment-form" action="{% url 'feed:comment_feed' feed.pk %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    {{ form.content }}
                </div>
                <button type="submit" class="btn btn-primary">Post</button>
            </form>
  
        </section>
{% endblock content %}
{% block script %}
        {% comment %} <script src="{% static 'js/feed_detail.js' %}"></script> {% endcomment %}
{% endblock script %}

feed/templates/feed/feed_list.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}
    <section class="feed-form">
        <form action="{% url 'feed:feed_create' %}" method="post">
            {% csrf_token %}
            <div class="form-groups">
                {{ feed_form.content }}
            </div>
            <button type="submit" class="btn btn-primary">Post</button>
        </form>
    </section>
    <section class="feeds">
        {% if feeds %}
            <h1>Feeds</h1>
        {% endif %}
        {% for feed in feeds %}
           {% if feed.user != request.user %}
           <article class="feed">
            <header class="feed-header">
                <a href="{% url 'profile' feed.user.pk %}" class="feed-user">{{ feed.user }}</a>
                <span class="feed-date">{{ feed.created | naturaltime }}</span>
            </header>
            <div class="feed-body">
                <p>{{ feed.content }}</p>
            </div>
            <footer class="feed-footer">
                <div class="feed-info">
                    <a href="{% url 'feed:like_feed' feed.pk %}" class="feed-like-icon" data-feed-id="{{feed.pk }}" data-action=
                    {% if request.user in feed.likes.all %}
                    'unlike'
                    {% endif %}
                    'like'
                    >
                        {% if request.user in feed.likes.all %}
                        👍
                        {% else %}
                        👍🏼
                        {% endif %}
                    </a>
                    <div class="feed-like-info">
                        <span class="feed-like-number">{{ feed.likes.all | length}}</span>
                        <span>like{{ feed.likes.count| pluralize}}</span>
                    </div>
                    <div class="feed-comment-info">
                        <span class="feed-comment-number">{{ feed.comments.all | length}}</span>
                        <span>comment{{ feed.comments.count| pluralize}}</span>
                    </div>
                    <a href="{% url 'feed:feed_detail' feed.pk %}" class="btn btn-primary">View</a>
                </div>
            </footer>
            <div class="feed-comments">
                <p>Comments</p>
                {% for comment in feed.comments.all|slice:2 %}
                
                <div class="comment">
                    <a href="{% url 'profile' comment.user.pk %}"><strong>{{ comment.user }} </strong></a>
                    <p>{{ comment.content|truncatechars:20 }}</p>
                </div>
                {% empty %}
                    
                        {% if feed.user != request.user %}
                        
                            Be the first one to comment on this post.
                        {% endif %}
                {% endfor %}
            </div>
            <form class="comment-form" action="{% url 'feed:comment_feed' feed.id %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    {{ comment_form.content }}
                </div>
                <button type="submit" class="btn btn-primary">Comment</button>
            </form>
          </article>
           {% endif %}
        {% empty %}
            No posts yet. Be the first one to post.
        {% endfor %}
    </section>
{% endblock content %}

{% block script %}
    <script>
        {% comment %} const likeBtns = document.querySelectorAll('.feed-like-icon')
        for(let likeBtn of likeBtns){
            likeBtn.addEventListener('click', e =>{
                e.preventDefault()
                let feedId = likeBtn.getAttribute('data-feed-id')
               
            })
        } {% endcomment %}
        
    </script>
{% endblock script %}