config/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include
from landing.views import home_view

from feed.models import Feed
from account.models import Profile
from django.contrib.auth.models import User


urlpatterns = [
    path('accounts/', include('account.urls')),
    path('accounts/', include(('django.contrib.auth.urls', 'auth'), namespace='accounts')),
    path('admin/', admin.site.urls),
    path('feeds/', include('feed.urls')),
    path('notifications/', include('notification.urls')),
    path('messages/', include('direct_message.urls')),
    path('search/', include('landing.urls') ),
    path('', include('landing.urls')),

    # api routes

    path('api/feeds/', include(('feed.api.urls', 'feed_api'))),

]

direct_message/urls.py
from django.urls import path

from .views import message_list_view, message_detail_view, message_send_view

app_name = 'direct_message'

urlpatterns = [
    path('', message_list_view, name='message_list'),
    path('<int:pk>/send/', message_send_view, name='message_send'),
    path('<int:pk>/', message_detail_view, name='message_detail'),
]

feed/urls.py
from django.urls import path
from .views import feed_list, feed_create_view, comment_feed, like_feed, feed_detail, api_like_feed


app_name = 'feed'
urlpatterns = [
   
    path("", feed_list, name="feed_list"),
    path("", feed_list, name="feed_list"),
    path('<int:pk>/', feed_detail, name='feed_detail'),
    path("create/", feed_create_view, name="feed_create"),
    path("<int:pk>/comments/create", comment_feed, name="comment_feed"),
    path("<int:pk>/likes/add", like_feed, name="like_feed"),
]

landing/urls.py
from django.urls import path

from .views import home_view
from landing.views import search
app_name = 'landing'
urlpatterns = [
    path('', home_view, name='home'),
    path('search/', search, name="search" ),
]

notification/urls.py
from django.urls import path
from .views import  notification_list, notification_detail

app_name = 'notification'
urlpatterns = [
    path('', notification_list, name='notification_list'),
    path('<pk>/', notification_detail, name='notification_detail'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    <header>
        <div class="container">
            <nav>
                <div class="logo"><a href="{% url 'landing:home' %}">sn📷</a></div>
                <ul>
                    <li><a href="{% url 'landing:home' %}">Home </a></li>
                    {% if request.user.is_authenticated %}
                        <li><a class="notification-link" href="{% url 'notification:notification_list' %}">Notifications 
                            {% if notification_counts > 0 %}
                                <span class="notification-counts">{{ notification_counts }}</span>
                            {% endif %}
                            </a>
                        </li>
                        <li><a class="notification-link"href="{% url 'direct_message:message_list' %}">Messages 
                            {% if message_counts > 0 %}
                                <span class="notification-counts">{{ message_counts }}</span>
                            {% endif %}
                            </a>
                        </li>
                        <li><a href="{% url 'feed:feed_list' %}">Feeds </a></li>
                        {% comment %} <li><a href="{% url 'feed:feed_create' %}">Post a Feeds </a></li> {% endcomment %}
                    
                </ul>
                <form class="search-form" action="{% url 'landing:search' %}" method="get">
                    <div class="form-group">
                        <input type="search" name="query" id="search-input" class="search-input">
                    </div>
                    <button class="btn btn-primary" type="submit">search</button>
                </form>
                {% endif %}
                <ul class="end">
                    {% if request.user.is_authenticated %}
                    
                        <li><a href="{% url 'profile' %}">Hello, {{ request.user.username }}</a></li>
                        <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'accounts:login' %}">Login</a></li>
                        <li><a href="{% url 'signup' %}">Register</a></li>
                    {% endif %}
                    
                </ul>
            </nav>
        </div>
    </header>
    <main class="main">
        <section class="container">
            {% block content %}
            
            {% endblock content %}
        </section>
    </main>
    <footer class="footer">
        <section class="container">
            <div class="copyright-info">
                <h4>sn</h4>
                <p>All right reserved &copy; <span class="year"></span></p>
            </div>
        </section>
    </footer>
    {% block script %}

    {% endblock script %}
    <script src="{% static 'js/base.js' %}"></script>
</body>
</html>

templates/search.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
    <section class="search">
        {% if profiles %}
            <article class='profile'>
                <h3>People</h3>
                {% for profile in profiles %}
                    <div class="profile-list-info">
                        <div>
                            <a class="username" href="{% url 'profile' profile.pk %}"><strong> {{ profile.user.username }}</strong></a>
                            <div class="stat">
                                <span> {{ profile.following.all|length}} Following </span>
                                <span> {{ profile.followers.all|length}} Followers </span>
                                <span>{{  profile.user.feeds.all|length}} Posts</span>
                            </div>
                        </div>
                        <a href="{% url 'follow' profile.pk %}" class="btn btn-follow">
                            {% if request.user.profile in profile.followers.all %}
                                Unfollow
                            {% else %}
                                Follow
                            {% endif %}
                        </a>
                    </div>
                {% endfor %}
            </article>
        {% endif %}
        {% if feeds %}
        <article class="feeds">
            <h3>Feeds</h3>
            {% for feed  in feeds %}
                <div class="feed">
                    {% comment %} <a href="{% url 'feed:feed_detail' feed.pk %}">{{ feed }}</a> {% endcomment %}
                    <header class="feed-header">
                        <a href="{% url 'profile' feed.user.pk %}" class="feed-user">{{ feed.user }}</a>
                        <span class="feed-date">{{ feed.created | naturaltime }}</span>
                    </header>
                    <div class="feed-body">
                        <p>{{ feed.content }}</p>
                    </div>
                    <footer class="feed-footer">
                        <div class="feed-info">
                            <a href="{% url 'feed:like_feed' feed.pk %}" class="feed-like-icon" data-feed-id="{{feed.pk }}" data-action=
                            {% if request.user in feed.likes.all %}
                            'unlike'
                            {% endif %}
                            'like'
                            >
                                {% if request.user in feed.likes.all %}
                                👍
                                {% else %}
                                👍🏼
                                {% endif %}
                            </a>
                            <div class="feed-like-info">
                                <span class="feed-like-number">{{ feed.likes.all | length}}</span>
                                <span>like{{ feed.likes.count| pluralize}}</span>
                            </div>
                            <div class="feed-comment-info">
                                <span class="feed-comment-number">{{ feed.comments.all | length}}</span>
                                <span>comment{{ feed.comments.count| pluralize}}</span>
                            </div>
                            <a href="{% url 'feed:feed_detail' feed.pk %}" class="btn btn-secondary">View</a>
                        </div>
                    </footer>
                </div>
            {% empty %}
                <p> no posts.</p>
            {% endfor %}
        </article>
        {% endif %}
    </section>
{% endblock content %}