config/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include
from landing.views import home_view

from feed.models import Feed
from account.models import Profile
from django.contrib.auth.models import User


urlpatterns = [
    path('accounts/', include('account.urls')),
    path('accounts/', include(('django.contrib.auth.urls', 'auth'), namespace='accounts')),
    path('admin/', admin.site.urls),
    path('feeds/', include('feed.urls')),
    path('notifications/', include('notification.urls')),
    path('messages/', include('direct_message.urls')),
    path('search/', include('landing.urls') ),
    path('', include('landing.urls')),

    # api routes

    path('api/feeds/', include(('feed.api.urls', 'feed_api'))),

]

feed/urls.py
from django.urls import path
from .views import feed_list, feed_create_view, comment_feed, like_feed, feed_detail, api_like_feed


app_name = 'feed'
urlpatterns = [
   
    path("", feed_list, name="feed_list"),
    path("", feed_list, name="feed_list"),
    path('<int:pk>/', feed_detail, name='feed_detail'),
    path("create/", feed_create_view, name="feed_create"),
    path("<int:pk>/comments/create", comment_feed, name="comment_feed"),
    path("<int:pk>/likes/add", like_feed, name="like_feed"),
]

notification/urls.py
from django.urls import path
from .views import  notification_list, notification_detail

app_name = 'notification'
urlpatterns = [
    path('', notification_list, name='notification_list'),
    path('<pk>/', notification_detail, name='notification_detail'),
]

notification/models.py
from django.db import models
from django.conf import settings

class Notification(models.Model):
    NOTIFICATION_TYPE = (
        ('like', 'Like'),
        ('follow', 'Follow'),
        ('post', 'Post'),
        ('comment', 'Comment')
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    type = models.CharField(max_length=10, choices=NOTIFICATION_TYPE)
    target_model = models.PositiveIntegerField(null=True)
    target = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='notifications')
    is_seen = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.type

notification/views.py
from django.shortcuts import get_object_or_404, redirect, render

from .models import Notification

def notification_list(request):
    notifications = Notification.objects.filter(target=request.user, is_seen=False)

    context = {
        'notifications' : notifications
    }
    return render(request, 'notification/notification_list.html', context)

def notification_detail(request, pk):
    notification = get_object_or_404(Notification, pk=pk)
    notification.is_seen = True
    notification.save()
    if notification.type == 'follow':
        return redirect('profile', pk=notification.target_model)
    return redirect('feed:feed_detail', pk=notification.target_model)
        

notification/templates/notification/notification_list.html
{% extends 'base.html' %}

{% block content %}
    <section class="notifications">
        {% for notification in notifications %}
            <p>Notifications</p>
            <div >
                {% comment %} <a href="{% url 'profile' notification.user.profile.pk %}"><strong>{{ notification.user.username }}</strong></a> {% endcomment %}
                {% if notification.type == 'like' %}
                    <p class="notification-info"><a href="{% url 'notification:notification_detail' notification.pk %}"><strong>{{ notification.user.username }}</strong> liked your post</a></p>
                {% elif notification.type == 'comment' %}
                    <p class="notification-info"><a href="{% url 'notification:notification_detail' notification.pk %}"><strong>{{ notification.user.username }}</strong> commented on your post</a></p>
                {% elif notification.type == 'follow' %}
                    <p class="notification-info"><a href="{% url 'notification:notification_detail' notification.pk %}"><strong>{{ notification.user.username }}</strong> started following you</a></p>
                {% endif %}
                {% empty %}
                    <p class="notification-info"> You have no notification</p>
                {% endfor %}
            </div>
    </section>
{% endblock content %}